@Library('pipeline-library')_

pipeline {

  agent any

  environment {
    RUN_RESET_PLATFORM_STEP  = false
    RUN_TESTS_STEP           = false
    RUN_NOTIFY_STEP          = true
    RUN_SONAR_STEP           = false
    RUN_PRODUCTION_PACKAGING = true
    HCS_PACKAGING            = false

    BUILD_MODE               = 'pr-builder'
  
    STOREFRONT_NAME          = 'athenasstorefront'
    PROJECT_PACKAGE          = 'com.sap.cd.b2bmvp'
    ENVIRONMENT_NAME         = 'local'
 
    PLATFORM_HOME            = 'hybris/bin/platform'
    BINARIES_HOME            = 'hybris/bin/'
    HYBRIS_HOME              = 'hybris/'
    ANT_INSTALATION          = 'hybris-ant'
    HCS_PACKAGES_FOLDER      = '/Users/i848340/hcs_packages/'

    SLACK_CHANNEL            = 'pipelines'

    JUNIT_RESULT             = 'hybris/log/junit/TESTS-TestSuites.xml'
     
    //TODO 
    HYBRIS_ZIP               = '../../../../binaries/hybris64.zip'

    //SCANNER_HOME = tool 'SonarQube';
  }

  stages {
    stage('Log Info') {
      steps {           
          echo "Branch: ${env.BRANCH_NAME} "
          echo "Commit: ${env.GIT_COMMIT} "
          echo "Build mode: ${env.BUILD_MODE}"
      }
    }

    stage('Reset Platform') {
      when {
          beforeAgent true
          environment name: 'RUN_RESET_PLATFORM_STEP', value: 'true'
      }
      steps {           
        erasePlatform()
        unzipPlatform() 
      }
    }
    
    stage('Checkout code from SCM') {
      steps {   
        checkout scm
      }
    }

    stage('Build') {
      when {
          beforeAgent true
          environment name: 'RUN_PRODUCTION_PACKAGING', value: 'false'
      }
      steps {
        antBuilds()
      }
    }

    stage('Generate Production Package') {
      when {
          beforeAgent true
          environment name: 'RUN_PRODUCTION_PACKAGING', value: 'true'
      }
      steps {   
        generateProductionPackage true
      }
    }

    stage('Run Tests') {
      when {
          beforeAgent true
          environment name: 'RUN_TESTS_STEP', value: 'true'
      }
      steps {   
        runTests()
      }
    }

    stage('SonarQube') {
      when {
          beforeAgent true
          environment name: 'RUN_SONAR_STEP', value: 'true'
      }
      steps {   
        withSonarQubeEnv('SonarQube') {
          sh "ls -al"
          sh "${env.SCANNER_HOME}/bin/sonar-scanner -Djavax.net.debug=all -Djavax.net.debug=ssl:handshake -Dproject.settings=./sonar.properties"
        }   
      }
    }

    stage('Notify') {
      when {
          beforeAgent true
          environment name: 'RUN_NOTIFY_STEP', value: 'true'
      }
      steps {   
        notifySlack "Hybris is up and running! Branch: ${env.BRANCH_NAME} // Commit: ${env.GIT_COMMIT}", 'pipelines'
      }
    }
  }
}
