@Library('pipeline-library')_


pipeline {

  agent any

  environment {
    PLATFORM_HOME = 'hybris/bin/platform'
    BINARIES_HOME = 'hybris/bin/'
    HYBRIS_HOME = 'hybris/'
    HYBRIS_ZIP = '../../../../binaries/hybris64.zip'
  }

  stages {
    stage('Erase Platform') {
      steps {
    
     //   erasePlatform env.BINARIES_HOME
      //  unzipPlatform env.BINARIES_HOME,env.HYBRIS_ZIP

        //dir (env.HYBRIS_HOME) {
        //  sh '. ./setantenv.sh && ant envconfig'
        //}

        //timeout(time:5, unit:'DAYS') {
        //  input message:'Approve deployment?', submitter: 'admin'
       // }
      }
    }
    stage('Build') {
      steps {

        antBuilds env.PLATFORM_HOME, env.HYBRIS_HOME

        notifySlack "Hybris is up and running! Branch: ${env.BRANCH_NAME} // Commit: ${env.GIT_COMMIT}", 'pipelines'
      }
    }
  }
}
